### ISSUE TITLE
** incremental compilation may be fatally broken for this module **

### ISSUE THREAD

**Issue by michaelfliegner** [GenieFramework/SearchLightPostgreSQL.jl#17]
WARNING: Method definition remove_index(Union{String, Symbol}, Union{String, Symbol}) in module Migration at /home/gitpod/.julia/packages/SearchLight/2TRYg/src/Migration.jl:539 overwritten in module SearchLightPostgreSQL at /home/gitpod/.julia/packages/SearchLightPostgreSQL/cIJM3/src/SearchLightPostgreSQL.jl:370.
  ** incremental compilation may be fatally broken for this module **

Status `/workspace/BitemporalReactive.jl/Project.toml`
  [340e8cb6] SearchLight v2.8.0

Status `/workspace/BitemporalReactive.jl/Project.toml`
  [4327cdd6] SearchLightPostgreSQL v2.3.2

**Comment by essenciary** [comment]
Ugh thanks - sounds familiar, I'll take a look.

**Comment by essenciary** [comment]
@michaelfliegner Does the latest release fix it?

**Comment by michaelfliegner** [comment]
Yes
