### ISSUE TITLE
SearchLightPostgreSQL:370   add_column implementation contains an undefined expression

### ISSUE THREAD

**Issue by angstyloop** [GenieFramework/SearchLightPostgreSQL.jl#2]
The implementation of method `SearchLight.Migration.add_column` in module SearchLightPostgreSQL uses undefined expression `SearchLight.column` instead of function `SearchLight.Migration.column`.

**Comment by essenciary** [comment]
Thanks - I patched and submitted to register a version bump

**Comment by angstyloop** [comment]
thanks!
