### ISSUE TITLE
Support for range types

### ISSUE THREAD

**Issue by Kaeptenblaubaer** [GenieFramework/SearchLightPostgreSQL.jl#7]
Supporting range types would enable gist indices and thus make Genie fit for applications managing spatial and temporal data.

For instance for bitemporal data processing type mappings like these would be fine:

:ZonedDateTime => :TIMESTAMPTZ 
:Interval{ZonedDateTime, Closed, Open} => :TSTZRANGE

**Comment by essenciary** [comment]
@Kaeptenblaubaer can you please add whatever is needed and make a PR if all is good? Happy to merge it.

**Comment by Kaeptenblaubaer** [comment]
Thank You. But where to start, where is the type mapping used?

**Comment by essenciary** [comment]
I think we can close this - sorry, I missed the question.
